name: json_object
version: 1.0.15+2
author: Chris Buckett <chrisbuckett@gmail.com>
description: Allow use of JSON Maps in dot notation format
homepage: https://github.com/chrisbu/dartwatch-JsonObject
environment:
  sdk: '>=0.5.0+1.r21823'
dependencies:
  meta: '>=0.5.0+1 <0.6.0'
dev_dependencies:
  unittest: '>=0.5.0+1 <0.6.0'
