name: json_object
version: 1.0.4
description: > 
  Allow use of JSON Maps in dot notation format
  M3 compatible
author: Chris Buckett <chrisbuckett@gmail.com>
homepage: https://github.com/chrisbu/dartwatch-JsonObject
dependencies:
  unittest: any