name: json_object
version: 1.0.10
author: Chris Buckett <chrisbuckett@gmail.com>
description: Allow use of JSON Maps in dot notation format
homepage: https://github.com/chrisbu/dartwatch-JsonObject
dependencies:
  unittest: any
